# Generated by Django 4.2.5 on 2023-10-10 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usertable',
            name='user',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='access_label',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='content',
            field=models.TextField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='title',
            field=models.TextField(default=-1),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user1_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user2_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user3_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
