# Generated by Django 4.2.5 on 2023-10-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_usertable_user_id_usertable_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
